---
title: "Bias"
author: "Matt Kosko"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(pbapply)

base_dir <- '~/Documents/HW/Research/CI/causalblb_test'

source(file.path(base_dir, 'code/helper_funcs.R'))

te <- 0.8
sigma <- 1
replications <- 500
r <- 100

base_nm <- 'bias_std_err'

image_path <- 'images'
dat_path <- 'data'


```


```{r}
dat <- as.data.table(readRDS(file.path(base_dir, dat_path, paste0(base_nm, '_tmp'), 'coverage.rds')))
```

# Coverage

## Percentile

```{r}
tmp <- dat[, .(lower = boot:::perc.ci(boot_reps)[4], upper = boot:::perc.ci(boot_reps)[5]), 
           by = c('subset_num', 'replication', 'n')][
          ,.(lower = mean(lower), upper = mean(upper)), by = c('replication', 'n')
        ]
tmp[, .(coverage = mean(lower <= te & upper >= te)), by = c('n')]
```


## Normal

```{r}
tmp <- dat[, .(lower = mean(boot_reps) - 1.96*sd(boot_reps), upper = mean(boot_reps) + 1.96*sd(boot_reps)), 
           by = c('subset_num', 'replication', 'n')][
          ,.(lower = mean(lower), upper = mean(upper)), by = c('replication', 'n')
        ]
tmp[, .(coverage = mean(lower <= te & upper >= te)), by = c('n')]
```



# Bias

```{r}
true_sd <- dat[, .(SD_full = mean(sd_full)), by = c('n')]
```

## ATE

```{r}
bias <- dat[, .(ATE = mean(boot_reps),
        SE = sd(boot_reps)), by = c('subset_num', 'replication', 'n')][
          , .(ATE = mean(ATE), SE = mean(SE)), by = c('replication', 'n')
        ]

ggplot(bias, aes(x = ATE)) +
  geom_histogram() +
  facet_wrap(~ n) +
  geom_vline(xintercept = te)
```

## Standard Error

```{r}
ggplot(bias, aes(x = SE)) +
  geom_histogram() +
  facet_wrap(~ n) +
  geom_vline(data = true_sd, aes(xintercept = sqrt(SD_full)))
```
